apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-deployment
  labels:
    app: inference
spec:
  replicas: 3
  selector:
    matchLabels:
      app: inference
  template:
    metadata:
      labels:
        app: inference
    spec:
      restartPolicy: Always
      containers:
      - name: inference
        image: mm12063/mm12063/stock-inference:6.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        volumeMounts:
          - name: stock-infer-pv
            mountPath: /home/app
      volumes:
        - name: stock-infer-pv
          persistentVolumeClaim:
            claimName: stock-data-volume


