apiVersion: v1
kind: Service
metadata:
  name: stock-infer-svc
  labels:
    app: infer
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: stock-infer